# deployments/user-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: shopnest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: node:18-alpine
          workingDir: /app
          command: ["node", "src/index.js"]
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: shopnest-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: shopnest-config
                  key: DB_PORT
            - name: DB_NAME
              value: "userdb"
            - name: DB_USERNAME
              value: "userservice"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shopnest-secrets
                  key: USER_DB_PASSWORD
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: shopnest-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: shopnest-config
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shopnest-secrets
                  key: REDIS_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: shopnest-secrets
                  key: JWT_SECRET
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: shopnest-config
                  key: NODE_ENV
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: shopnest
spec:
  selector:
    app: user-service
  ports:
    - port: 3001
      targetPort: 3001
  type: ClusterIP
